# ~/.codex/config.toml

disable_response_storage = true
show_reasoning_content = true

[model_providers.local]
name = "local"
base_url = "http://localhost:8080/v1"

[profiles.oss]
model = "gpt-oss:20b"
model_provider = "local"

#[sandbox]
#mode = "disabled" # You can safely leave this on now!

[projects."/home/jbfly/git/ai-ops"]
trust_level = "trusted"
